ProjectHMSClient/OrderSysClient/OrderSysClient/Controllers/UserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderSysClient.Controllers
{
    public class UserRegistrationController : Controller
    {
        // GET: userregistration
        public ActionResult Add()
        {
            string employee_user_name = (string)Session["employee_user_name"];
            string employee_id = (string)Session["employee_id"];
            string role_type_id = (string)Session["role_type_id"];
            string role_name = (string)Session["role_name"];
            string employee_name = (string)Session["employee_name"];
            string hospital_id = (string)Session["hospital_id"];

            if (employee_id == null || employee_user_name == null || role_type_id == null)
            {
                Response.Redirect("/Login/Index");
            }
            ViewBag.hospital_id = hospital_id;
            return View();
        }
        public ActionResult List()
        {
            string employee_user_name = (string)Session["employee_user_name"];
            string employee_id = (string)Session["employee_id"];
            string role_type_id = (string)Session["role_type_id"];
            string role_name = (string)Session["role_name"];
            string employee_name = (string)Session["employee_name"];
            string hospital_id = (string)Session["hospital_id"];

            if (employee_id == null || employee_user_name == null || role_type_id == null)
            {
                Response.Redirect("/Login/Index");
            }
            ViewBag.hospital_id = hospital_id;
            return View();
        }
    }
}

ProjectHMSClient/OrderSysClient/OrderSysClient/Views/userregistration/Add.cshtml
@{
    ViewBag.Title = "Add";
}
<div class="panel panel-success">
    <div class="panel-heading">&nbsp;&nbsp;
        <h3>Employee Registration</h3></div>
    <div id="kWindow"></div>
    <div class="panel-body">
        <div id="uesrTab">
            <div>
                <form id="frmUserInformation" style="padding: 10px;">
                    <input type="hidden" name="hospital_id" value='@ViewBag.hospital_id'>
                    <div class="row">
                        <div class="col-md-5">
                            <div class="col-md-3">
                                <label for="employee_name">Full Name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="k-textbox" name="employee_name" id="employee_name" placeholder="Employee Name" required validationmessage="Please Enter the Employee name" style="width: 100%;">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="col-md-3">
                                <label for="user_email">Email</label>
                            </div>
                            <div class="col-md-8">
                                <input type="email" class="k-textbox" name="employee_email" id="employee_email" placeholder="e.g. myname@example.net" required data-email-msg="Email format is not valid" style="width: 100%;">
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-md-5">
                            <div class="col-md-3">
                                <label for="employee_user_name">User name</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="k-textbox" name="employee_user_name" id="employee_user_name" style="width: 100%;">
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="col-md-3">
                                <label for="employee_password">Password</label>
                            </div>
                            <div class="col-md-8">
                                <input type="text" class="k-textbox" name="employee_password" id="employee_password" style="width: 100%;">
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="department_id">Department</label>
                            </div>
                            <div class="col-md-8"><input type="text" name="department_id" id="department_id" required data-max-msg="Please Select Department" style="width: 100%;">
                            </div>

                        </div>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="role_type_id">Role</label>
                            </div>
                            <div class="col-md-8"><input type="text" name="role_type_id" id="role_type_id" required data-max-msg="Please Select a Role" style="width: 100%;">
                            </div>
                        </div>

                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="joining_date">Joining Date</label>
                            </div>
                            <div class="col-md-8"><input type="text" name="joining_date" id="joining_date" style="width: 100%;">
                            </div>

                        </div>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="employee_adress">Address</label>
                            </div>
                            <div class="col-md-8"><input type="text" class="k-textbox" name="employee_address" id="employee_address" style="width: 100%;">
                            </div>

                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="designation">Designation</label>
                            </div>
                            <div class="col-md-8"><input type="text" class="" name="designation" id="designation" placeholder="example:administrator" required validationmessage="Please Enter the Employee Designation" style="width: 100%;">
                            </div>

                        </div>
                        <div class="col-md-5">
                            <div class="col-md-3"><label for="nid">NID</label>
                            </div>
                            <div class="col-md-8"><input type="number" class="k-textbox" name="nid" id="nid" pattern="\d{13}" placeholder="Enter a Thirteen digit number" required validationmessage="Enter at least Thirteen digits" style="width: 100%;">
                            </div>

                        </div>
                        <div class="clearfix"></div>
                        <br/>
                        <input type="button" id="user_info" class="k-button pull-left" value="Save Information">
                        @*<button type="submit" >Submit</button>*@

                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    var hospital_id = '@ViewBag.hospital_id';
    $(function () {
        $("#department_id").kendoComboBox({
            autoBind: true,
            placeholder: "-- Select Department--",
            dataTextField: "department_name",
            dataValueField: "department_id",
            /// cascadeFrom:institute_id,
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@UrlConfig.Action("GetAllDepartment", "Department")?hospital_id=" + hospital_id
                    }
                }
            }
        });
        $("#role_type_id").kendoComboBox({
            autoBind: true,
            placeholder: "-- Select Role Type--",
            dataTextField: "role_name",
            dataValueField: "role_type_id",
            dataSource: {
                type: "json",
                transport: {
                    read: {
                        url: "@UrlConfig.Action("GetAllRoleType", "RoleType")"
                    }
                }
            }
        });
        $("#designation").kendoComboBox({
            placeholder: "-- Select --",
            dataTextField: "designation_value",
            dataValueField: "designation",
            dataSource: [
                { designation: "Professor", designation_value: "Professor" },
                { designation: "Specialist", designation_value: "Specialist" },
                { designation: "Intern Doctor", designation_value: "Intern Doctor" },
                { designation: "Administrator", designation_value: "Administrator" },
                { designation: "Accounts", designation_value: "Accounts" },
                { designation: "Receptionist", designation_value: "Receptionist" }

            ]
        }).data("kendoComboBox");
        $("#joining_date").kendoDatePicker({
            animation: {
                close: {
                    effects: "fadeOut zoom:out",
                    duration: 300
                },
                open: {
                    effects: "fadeIn zoom:in",
                    duration: 300
                }
            }//,
            //format: "dd/MM/yyyy"
        });
    
    });
    $("#user_info").click(function () {
        var validator = $("#frmUserInformation").kendoValidator().data("kendoValidator");
        if (validator.validate()) {
            var fromData = $("#frmUserInformation").serializeArray();
            console.log(fromData);
            var emp = {};
            $.each(fromData, function (key, val) {
                emp[val.name] = val.value;
            });
            console.log(emp);
            $.ajax({
                type: "POST",
                url: "@UrlConfig.Action("Post","employee")",
                data: emp,
                dataType: "json",
                //contentType: "application/json",
                //contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    console.log(data);
                    if (data.output == "success") {
                        swal({
                            title: "success",
                            text: data.msg,
                            type: "success",
                            showCancelButton: false
                        }, function () {
                            window.location.href = '@Url.Action("List", "UserRegistration")';
                        });
                        return false;
                    } else {
                        swal("Alert !!!", data.msg, "warning");
                    }
                }
            });
        }
        
    });
</script>

ProjectHMSClient/OrderSysClient/OrderSysClient/Views/userregistration/List.cshtml
@{
    ViewBag.Title = "List";
}

<div class="k-grid  k-secondary" data-role="grid">
    <div class="k-toolbar k-grid-toolbar">
        <a class="k-button k-button-icontext k-grid-add" href="@Url.Action("Add", "UserRegistration")">
            <span class="k-icon k-add"></span>
            Add New Employee
        </a>
    </div>
</div>
<div id="grid"></div>

<script type="text/javascript">
    var hospital_id = '@ViewBag.hospital_id';
    $(document).ready(function () {
        var dataSource = new kendo.data.DataSource({
            pageSize: 20,
            transport: {
                read: {
                    url: "@UrlConfig.Action("GetAllEmployee", "Employee")?hospital_id="+hospital_id,
                    type: "GET"
                    
                },
                update: {
                    url: "@UrlConfig.Action("Put", "Employee")",
                    type: "PUT",
                    complete: function (e) {
                        jQuery("#grid").data("kendoGrid").dataSource.read();
                    }
                },
                destroy: {
                    url: "@UrlConfig.Action("DeleteData", "Employee")",
                    type: "DELETE",

                    complete: function (e) {
                        if (e.output == "success") {
                            swal("Sucessfull !!!", e.msg, "success");
                        }
                    }
                }
            },
            autoSync: false,
            schema: {
                errors: function (e) {
                    console.log(e.errors);
                    if (e.output === "error") {
                        console.log(e.output);
                    }
                },

                model: {
                    id: "employee_id",
                    fields: {
                        employee_id: {type:"number", editable: false, nullable: true },
                        employee_name: { type: "string" },
                        joining_date: { type: "date" },
                        department_name: { type: "string" },
                        department_id: { type: "string" },
                        designation: { type: "string" },
                        role_name: { type: "string" },
                        employee_email: { type: "string" },
                        role_type_id: { type: "string" },
                        employee_code: { type: "string", editable: false },
                        nid: { type: "number" },
                        employee_user_name: { type: "string" },
                        employee_password: {type:"string"},
                        employee_email: {type:"string"}

                    }
                }
            }
        });
        jQuery("#grid").kendoGrid({
            dataSource: dataSource,
            filterable: true,
            pageable: {
                refresh: true,
                input: true,
                pageSize: 20,
                numeric: false,
                pageSizes: [10, 20, 50]
            },
            sortable: true,
            groupable: true,
            resizable: true,

            columns: [
                { field: "employee_name", title: "Employee Name", width: "150px" },
                { field: "joining_date", title: "Joining Date", width: "150px", template: "#= kendo.toString(kendo.parseDate(joining_date, 'yyyy-MM-ddTHH:mm:ss'), 'MM/dd/yyyy') #" },
                { field: "department_id", title: "Department name", editor: departmentDropDownEditor, template: "#= department_name #", width: "150px" },
                { field: "designation", title: "Designation", width: "150px" },
                { field: "role_type_id", title: "Role Name", editor: roleDropDownEditor, template: "#= role_name #", width: "100px" },
                { field: "employee_code", title: "Employee Code", width: "100px" },
                { command: ["edit","destroy"], title: "Action", width: "230px" }
            ],
            editable: "inline"
        });
        function departmentDropDownEditor(container, options) {
            jQuery('<input required data-text-field="department_name" data-value-field="department_id" data-bind="value:' + options.field + '"/>')
                .appendTo(container)
                .kendoComboBox({
                    autoBind: false,
                    placeholder: "-- Select --",
                    dataSource: {
                        transport: {
                            read: {
                                url: "@UrlConfig.Action("GetAllDepartment", "Department")",
                                type: "GET"
                            }
                        }

                    },
                });
        };
        function roleDropDownEditor(container, options) {
            jQuery('<input required data-text-field="role_name" data-value-field="role_type_id" data-bind="value:' + options.field + '"/>')
                .appendTo(container)
                .kendoComboBox({
                    autoBind: false,
                    placeholder: "-- Select --",
                    dataSource: {
                        transport: {
                            read: {
                                url: "@UrlConfig.Action("GetAllRoleType", "RoleType")",
                                type: "GET"
                                    
                            }
                        }

                    },
                });
        };
    });
</script>